language: generic

sudo: required

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t leeseungryeol/react-test-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true  leeseungryeol/react-test-app npm test -- --coverage

after_success:
  - echo "Test Success"

deploy :
  edge : true
  provider : elasticbeantalk
  region : ap-northeast-2
  app : docker-react-app
  env : Dockerreactapp-env
  bucket_name : elasticbeanstalk-ap-northeast-2-469579819621
  bucket_path : docker-react-app
  on :
     branch : master

  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY